### ISSUE TITLE
[DOUBT] Multiple application modules in same project

### ISSUE THREAD

**Issue by pedrofsn** [jeziellago/FlowNav#14]
Can I handle multiples `flownav.main.module` with this library? 
I've multiple applications modules in my scenario, it's a kind of white label application.

We're using https://github.com/Tulioh/SweetFactory to handle multi module navigation, it's working well but unhappy this processors is not incremental.

**Comment by jeziellago** [comment]
Hi @pedrofsn,

We added support for that in version `0.4.4`, published right now 😁

**Comment by jeziellago** [comment]
You can add to `gradle.peoperties` yours application modules using `,`.
>  flownav.main.module=appmodule1,appmodule2,appmodule3

**Comment by pedrofsn** [comment]
I'll test soon as possible! Fastest feature delivery ever! huehue
