### ISSUE TITLE
lateinit property entryMap has not been initialized

### ISSUE THREAD

**Issue by pedrofsn** [jeziellago/FlowNav#16]
> java.lang.RuntimeException: Unable to create application br.X.X.App: kotlin.UninitializedPropertyAccessException: lateinit property entryMap has not been initialized
> [...]
> Caused by: kotlin.UninitializedPropertyAccessException: lateinit property entryMap has not been initialized

My modules:
- app_x_app: contains application class annotated with @FlowNavMain and started with FlowNavApp.start(getEntryMap()) in onCreate method. Use kapt processor and implementation of annotation.

- app_x_login: contains login activity annotated with @EntryFlowNav(NavigationKeys.FEATURE_LOGIN). Use kapt processor and implementation of annotation.

- router: contains a extension function to open login activity.  Use kapt processor, implementation of annotation and router implementation (as 'api') .

```
fun BaseActivity.openLoginWithoutHistory() {
    start(
        FEATURE_LOGIN,
        listOf(
            Intent.FLAG_ACTIVITY_NO_ANIMATION,
            Intent.FLAG_ACTIVITY_NEW_TASK,
            Intent.FLAG_ACTIVITY_CLEAR_TASK
        )
    )
}
```

The big vision is:

- app_x_app
- - app_x_login
- - router

In gradle.properties:

> flownav.main.module=app_x_app

What am I missing?

**Comment by ppjeziellago** [comment]
Change import of `getEntryMap` to `import com.flownav.router.extension.getEntryMap` and `clean & build` your project.

**Comment by jeziellago** [comment]
Change import of `getEntryMap` to `import com.flownav.router.extension.getEntryMap` and `clean & build` your project.

**Comment by pedrofsn** [comment]
You're right, I fixed import and it worked!
