### ISSUE TITLE
Is EntryMap generation cause to bugs when using "class.name" with obfuscation?

### ISSUE THREAD

**Issue by Moozart** [jeziellago/FlowNav#24]
Hi, good job.  I did not make decision about that is EntryMap generation cause to bugs when using "class.name" with obfuscation?

**Comment by jeziellago** [comment]
Hi @Moozart,

It works with proguard/R8 obfuscation.

To check it, you might todo: 
1. Open [sample](https://github.com/jeziellago/FlowNav/tree/master/sample) as gradle project in your Android Studio,
2. Change gradle.properties to `
android.enableR8.fullMode=true`
3. Generate `release` from `:app`
4. Install and run.

The sample app should work normally.
